"""Simple deterministic physics solver utilities."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Tuple

import math
import numpy as np

__all__ = ["RigidBody", "HeightField", "step_physics"]


@dataclass
class RigidBody:
    """Minimal rigid body representation for 2D collisions.

    Attributes
    ----------
    position:
        2D position vector.
    velocity:
        2D velocity vector.
    mass:
        Mass of the body; must be positive.
    radius:
        Radius of the circular body used for broad phase and collision
        response.  The solver is intentionally restricted to circles to keep
        the implementation compact and deterministic.
    """

    position: np.ndarray
    velocity: np.ndarray
    mass: float
    radius: float

    def __post_init__(self) -> None:
        if self.mass <= 0:
            raise ValueError("mass must be positive")
        if self.radius <= 0:
            raise ValueError("radius must be positive")
        self.position = np.asarray(self.position, dtype=np.float32)
        self.velocity = np.asarray(self.velocity, dtype=np.float32)


_DEF_DT = 1.0 / 60.0


@dataclass
class HeightField:
    """Simple 1D heightfield collision proxy.

    The field samples are spaced evenly along the X axis and represent the
    minimum allowed Y coordinate.  Bodies are kept above the sampled height
    plus their radius and may bounce with the configured restitution.
    """

    heights: np.ndarray
    x0: float = 0.0
    cell_size: float = 1.0

    def __post_init__(self) -> None:
        self.heights = np.asarray(self.heights, dtype=np.float32)
        if self.cell_size <= 0:
            raise ValueError("cell_size must be positive")

    def sample(self, x: float) -> float:
        """Return the height at horizontal coordinate ``x``."""

        idx = int(math.floor((x - self.x0) / self.cell_size))
        idx = max(0, min(int(len(self.heights) - 1), idx))
        return float(self.heights[idx])


def _broad_phase_pairs(bodies: List[RigidBody], cell_size: float) -> List[Tuple[int, int]]:
    """Return potential collision pairs using a uniform spatial grid.

    The grid ensures that only bodies within the same or neighboring cells are
    considered for collision resolution.  ``cell_size`` must be at least twice
    the maximum body radius to guarantee that no collisions are missed.
    """

    grid: Dict[Tuple[int, int], List[int]] = {}
    for idx, body in enumerate(bodies):
        cx = int(math.floor(body.position[0] / cell_size))
        cy = int(math.floor(body.position[1] / cell_size))
        grid.setdefault((cx, cy), []).append(idx)

    pairs = set()
    neighbors = (-1, 0, 1)
    for (cx, cy), indices in sorted(grid.items()):
        indices.sort()
        # Pairs within the cell
        for i in range(len(indices)):
            for j in range(i + 1, len(indices)):
                pairs.add((indices[i], indices[j]))
        # Neighboring cells
        for dx in neighbors:
            for dy in neighbors:
                if dx == 0 and dy == 0:
                    continue
                neigh = (cx + dx, cy + dy)
                other = grid.get(neigh)
                if not other:
                    continue
                for i in indices:
                    for j in other:
                        if i < j:
                            pairs.add((i, j))
                        else:
                            pairs.add((j, i))

    return sorted(pairs)


def step_physics(
    bodies: List[RigidBody],
    *,
    dt: float = _DEF_DT,
    iterations: int = 10,
    restitution: float = 1.0,
    cell_size: float | None = None,
    heightfield: HeightField | None = None,
    gravity: float = 0.0,
    damping: float = 0.0,
) -> None:
    """Advance ``bodies`` by ``dt`` using a sequential impulse solver.

    The solver performs the specified number of Gauss–Seidel iterations over
    potential collision pairs generated by a deterministic uniform grid
    broad-phase.  Circular body collisions are resolved with impulses and an
    optional :class:`HeightField` keeps bodies above terrain.
    Positions are integrated using the updated velocities.  The routine
    operates in-place and produces deterministic results given the same
    initial body states.

    Parameters
    ----------
    bodies:
        Mutable sequence of rigid bodies to simulate.
    dt:
        Time step for the simulation in seconds.
    iterations:
        Number of Gauss–Seidel iterations to perform.
    restitution:
        Coefficient of restitution used for collision response and
        heightfield bounces.
    cell_size:
        Size of the uniform grid cells used for the broad-phase step.  When
        ``None`` a suitable value is derived from the body radii.
    heightfield:
        Optional heightfield collision proxy.  If provided, bodies are kept
        above the sampled ground height plus their radius.
    gravity:
        Constant acceleration applied on the negative Y axis.  The same value
        is applied to all bodies each step and is suitable for deterministic
        global gravity.
    damping:
        Linear velocity damping factor.  ``0`` disables damping.  The value is
        interpreted as a per-second coefficient and is applied uniformly to all
        bodies.  Higher values result in stronger drag and the term is clamped
        to ``[0, 1]`` for stability.
    """

    if dt <= 0:
        raise ValueError("dt must be positive")
    if iterations < 1:
        raise ValueError("iterations must be at least 1")
    if cell_size is not None and cell_size <= 0:
        raise ValueError("cell_size must be positive")
    if damping < 0:
        raise ValueError("damping must be non-negative")

    # Apply constant acceleration, linear damping, and integrate positions
    # using the updated velocities.  This mirrors the typical order of
    # operations in a semi-implicit Euler integrator and ensures collisions are
    # detected when bodies move into contact within the same step.
    damp_factor = max(0.0, 1.0 - damping * dt)
    for body in bodies:
        if gravity != 0.0:
            body.velocity[1] += gravity * dt
        if damping != 0.0:
            body.velocity *= damp_factor
        body.position += body.velocity * dt

    inv_masses = [1.0 / b.mass for b in bodies]

    if cell_size is None:
        max_radius = max((b.radius for b in bodies), default=0.0)
        cell_size = max_radius * 2.0 if max_radius > 0.0 else 1.0

    pairs = _broad_phase_pairs(bodies, cell_size)

    for _ in range(iterations):
        for i, j in pairs:
            a = bodies[i]
            b = bodies[j]
            delta = b.position - a.position
            dist = float(np.linalg.norm(delta))
            min_dist = a.radius + b.radius
            if dist >= min_dist or dist == 0.0:
                continue
            n = delta / dist
            rel_vel = float(np.dot(b.velocity - a.velocity, n))
            if rel_vel > 0.0:
                continue
            j_impulse = -(1.0 + restitution) * rel_vel
            j_impulse /= inv_masses[i] + inv_masses[j]
            impulse = j_impulse * n
            a.velocity -= impulse * inv_masses[i]
            b.velocity += impulse * inv_masses[j]

    if heightfield is not None:
        for body in bodies:
            ground = heightfield.sample(float(body.position[0])) + body.radius
            if body.position[1] < ground:
                body.position[1] = ground
                if body.velocity[1] < 0.0:
                    body.velocity[1] = -body.velocity[1] * restitution
