"""Collision detection and physics simulation.

This module provides the sequential impulse solver for 2D and 3D physics:
- step_physics: 2D physics simulation
- step_physics_3d: 3D hybrid physics simulation
- detect_collision: Collision detection utilities
"""
from __future__ import annotations

from typing import Dict, List, Tuple

import math
import numpy as np

from procengine.physics.bodies import RigidBody, RigidBody3D, Vec3
from procengine.physics.heightfield import HeightField, HeightField2D


__all__ = ["step_physics", "step_physics_3d", "detect_collision"]


_DEF_DT = 1.0 / 60.0


def _broad_phase_pairs(bodies: List[RigidBody], cell_size: float) -> List[Tuple[int, int]]:
    """Return potential collision pairs using a uniform spatial grid.

    The grid ensures that only bodies within the same or neighboring cells are
    considered for collision resolution.  ``cell_size`` must be at least twice
    the maximum body radius to guarantee that no collisions are missed.
    """

    grid: Dict[Tuple[int, int], List[int]] = {}
    for idx, body in enumerate(bodies):
        cx = int(math.floor(body.position[0] / cell_size))
        cy = int(math.floor(body.position[1] / cell_size))
        grid.setdefault((cx, cy), []).append(idx)

    pairs = set()
    neighbors = (-1, 0, 1)
    for (cx, cy), indices in sorted(grid.items()):
        indices.sort()
        # Pairs within the cell
        for i in range(len(indices)):
            for j in range(i + 1, len(indices)):
                pairs.add((indices[i], indices[j]))
        # Neighboring cells
        for dx in neighbors:
            for dy in neighbors:
                if dx == 0 and dy == 0:
                    continue
                neigh = (cx + dx, cy + dy)
                other = grid.get(neigh)
                if not other:
                    continue
                for i in indices:
                    for j in other:
                        if i < j:
                            pairs.add((i, j))
                        else:
                            pairs.add((j, i))

    return sorted(pairs)


def detect_collision(a: RigidBody, b: RigidBody) -> bool:
    """Check if two circular bodies are overlapping."""
    delta = b.position - a.position
    dist = float(np.linalg.norm(delta))
    return dist < (a.radius + b.radius)


def step_physics(
    bodies: List[RigidBody],
    *,
    dt: float = _DEF_DT,
    iterations: int = 10,
    restitution: float = 1.0,
    cell_size: float | None = None,
    heightfield: HeightField | None = None,
    gravity: float = 0.0,
    damping: float = 0.0,
) -> None:
    """Advance ``bodies`` by ``dt`` using a sequential impulse solver.

    The solver performs the specified number of Gauss–Seidel iterations over
    potential collision pairs generated by a deterministic uniform grid
    broad-phase.  Circular body collisions are resolved with impulses and an
    optional :class:`HeightField` keeps bodies above terrain.
    Positions are integrated using the updated velocities.  The routine
    operates in-place and produces deterministic results given the same
    initial body states.

    Parameters
    ----------
    bodies:
        Mutable sequence of rigid bodies to simulate.
    dt:
        Time step for the simulation in seconds.
    iterations:
        Number of Gauss–Seidel iterations to perform.
    restitution:
        Coefficient of restitution used for collision response and
        heightfield bounces.
    cell_size:
        Size of the uniform grid cells used for the broad-phase step.  When
        ``None`` a suitable value is derived from the body radii.
    heightfield:
        Optional heightfield collision proxy.  If provided, bodies are kept
        above the sampled ground height plus their radius.
    gravity:
        Constant acceleration applied on the negative Y axis.  The same value
        is applied to all bodies each step and is suitable for deterministic
        global gravity.
    damping:
        Linear velocity damping factor.  ``0`` disables damping.  The value is
        interpreted as a per-second coefficient and is applied uniformly to all
        bodies.  Higher values result in stronger drag and the term is clamped
        to ``[0, 1]`` for stability.
    """

    if dt <= 0:
        raise ValueError("dt must be positive")
    if iterations < 1:
        raise ValueError("iterations must be at least 1")
    if cell_size is not None and cell_size <= 0:
        raise ValueError("cell_size must be positive")
    if damping < 0:
        raise ValueError("damping must be non-negative")

    # Apply constant acceleration, linear damping, and integrate positions
    # using the updated velocities.  This mirrors the typical order of
    # operations in a semi-implicit Euler integrator and ensures collisions are
    # detected when bodies move into contact within the same step.
    damp_factor = max(0.0, 1.0 - damping * dt)
    for body in bodies:
        if gravity != 0.0:
            body.velocity[1] += gravity * dt
        if damping != 0.0:
            body.velocity *= damp_factor
        body.position += body.velocity * dt

    inv_masses = [1.0 / b.mass for b in bodies]

    if cell_size is None:
        max_radius = max((b.radius for b in bodies), default=0.0)
        cell_size = max_radius * 2.0 if max_radius > 0.0 else 1.0

    pairs = _broad_phase_pairs(bodies, cell_size)

    for _ in range(iterations):
        for i, j in pairs:
            a = bodies[i]
            b = bodies[j]
            delta = b.position - a.position
            dist = float(np.linalg.norm(delta))
            min_dist = a.radius + b.radius
            if dist >= min_dist or dist == 0.0:
                continue
            n = delta / dist
            rel_vel = float(np.dot(b.velocity - a.velocity, n))
            if rel_vel > 0.0:
                continue
            j_impulse = -(1.0 + restitution) * rel_vel
            j_impulse /= inv_masses[i] + inv_masses[j]
            impulse = j_impulse * n
            a.velocity -= impulse * inv_masses[i]
            b.velocity += impulse * inv_masses[j]

    if heightfield is not None:
        for body in bodies:
            ground = heightfield.sample(float(body.position[0])) + body.radius
            if body.position[1] < ground:
                body.position[1] = ground
                if body.velocity[1] < 0.0:
                    body.velocity[1] = -body.velocity[1] * restitution


def step_physics_3d(
    bodies: List[RigidBody3D],
    *,
    dt: float = _DEF_DT,
    iterations: int = 10,
    restitution: float = 0.5,
    cell_size: float | None = None,
    heightfield: HeightField2D | None = None,
    gravity: float = -9.8,
    damping: float = 0.0,
) -> None:
    """Advance 3D physics bodies using hybrid 2D+height approach.

    The solver uses a two-phase approach:
    1. Y-axis: Apply gravity, integrate Y position, resolve terrain collision
    2. XZ-plane: Project to 2D, run sequential impulse solver, apply back

    This preserves the existing deterministic 2D solver while adding vertical
    motion and terrain interaction.

    Parameters
    ----------
    bodies:
        Mutable list of 3D rigid bodies to simulate.
    dt:
        Time step in seconds.
    iterations:
        Gauss-Seidel iterations for 2D collision resolution.
    restitution:
        Coefficient of restitution for collisions.
    cell_size:
        Broad-phase grid cell size (None = auto).
    heightfield:
        Optional 2D heightfield for terrain collision.
    gravity:
        Gravity acceleration (applied to Y axis, typically negative).
    damping:
        Linear velocity damping factor per second.
    """
    if dt <= 0:
        raise ValueError("dt must be positive")
    if iterations < 1:
        raise ValueError("iterations must be at least 1")
    if cell_size is not None and cell_size <= 0:
        raise ValueError("cell_size must be positive")
    if damping < 0:
        raise ValueError("damping must be non-negative")

    if not bodies:
        return

    # Phase 1: Y-axis gravity and terrain collision
    damp_factor = max(0.0, 1.0 - damping * dt)

    for body in bodies:
        # Apply gravity to Y velocity
        body.velocity = Vec3(
            body.velocity.x,
            body.velocity.y + gravity * dt,
            body.velocity.z,
        )

        # Apply damping to all velocity components
        if damping != 0.0:
            body.velocity = body.velocity * damp_factor

        # Integrate Y position
        body.position = Vec3(
            body.position.x,
            body.position.y + body.velocity.y * dt,
            body.position.z,
        )

        # Terrain collision (Y axis)
        body.grounded = False
        if heightfield is not None:
            ground = heightfield.sample(body.position.x, body.position.z) + body.radius
            if body.position.y < ground:
                body.position = Vec3(body.position.x, ground, body.position.z)
                if body.velocity.y < 0.0:
                    body.velocity = Vec3(
                        body.velocity.x,
                        -body.velocity.y * restitution,
                        body.velocity.z,
                    )
                body.grounded = True

    # Phase 2: XZ plane collision using existing 2D solver
    # Project all bodies to 2D on XZ plane
    bodies_2d = [body.to_2d() for body in bodies]

    # Run 2D physics step (without gravity/heightfield - we handle those in 3D)
    step_physics(
        bodies_2d,
        dt=dt,
        iterations=iterations,
        restitution=restitution,
        cell_size=cell_size,
        heightfield=None,  # Already handled in phase 1
        gravity=0.0,       # Already handled in phase 1
        damping=0.0,       # Already handled in phase 1
    )

    # Apply 2D results back to 3D bodies
    for body_3d, body_2d in zip(bodies, bodies_2d):
        body_3d.apply_2d_result(body_2d)
