/**
 * @file launcher.cpp
 * @brief Standalone launcher for Procedural Engine with embedded Python.
 *
 * This launcher creates a native executable that:
 * 1. Embeds the Python interpreter
 * 2. Initializes the procengine_cpp module
 * 3. Runs main.py as the entry point
 *
 * Benefits over pure PyInstaller:
 * - Faster startup (no archive extraction)
 * - Better integration with Vulkan/graphics
 * - More control over Python initialization
 * - Can statically link procengine_cpp
 *
 * Build with CMake:
 *   cmake .. -DBUILD_LAUNCHER=ON
 *   cmake --build . --target ProceduralEngine
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <iostream>
#include <string>
#include <filesystem>
#include <vector>

#ifdef _WIN32
#include <windows.h>
#define PATH_SEP "\\"
#else
#include <unistd.h>
#define PATH_SEP "/"
#endif

namespace fs = std::filesystem;

// Forward declaration of the module init function
// This is generated by pybind11 and linked statically or dynamically
extern "C" PyObject* PyInit_procengine_cpp();

/**
 * Get the directory containing this executable.
 */
std::string get_executable_dir() {
#ifdef _WIN32
    char path[MAX_PATH];
    GetModuleFileNameA(nullptr, path, MAX_PATH);
    std::string exe_path(path);
    return exe_path.substr(0, exe_path.find_last_of("\\/"));
#else
    char path[PATH_MAX];
    ssize_t len = readlink("/proc/self/exe", path, sizeof(path) - 1);
    if (len != -1) {
        path[len] = '\0';
        std::string exe_path(path);
        return exe_path.substr(0, exe_path.find_last_of("/"));
    }
    // Fallback: use current directory
    return fs::current_path().string();
#endif
}

/**
 * Initialize Python paths for embedded distribution.
 */
void setup_python_paths(const std::string& exe_dir) {
    // Build the Python path:
    // 1. lib/ - Standard library (python312.zip or lib/pythonX.Y)
    // 2. lib/site-packages/ - Third-party packages
    // 3. . (exe_dir) - Our Python modules

    std::vector<std::wstring> paths;

#ifdef _WIN32
    // Windows: python312.zip for stdlib, DLLs for extensions
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"\\python312.zip");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"\\DLLs");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"\\lib");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"\\lib\\site-packages");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()));
#else
    // Linux/macOS: lib/pythonX.Y for stdlib
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"/lib/python3.12");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"/lib/python3.12/lib-dynload");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()) + L"/lib/python3.12/site-packages");
    paths.push_back(std::wstring(exe_dir.begin(), exe_dir.end()));
#endif

    // Build path string
    std::wstring path_str;
    for (size_t i = 0; i < paths.size(); ++i) {
        if (i > 0) {
#ifdef _WIN32
            path_str += L";";
#else
            path_str += L":";
#endif
        }
        path_str += paths[i];
    }

    Py_SetPath(path_str.c_str());
}

/**
 * Register our built-in module with Python.
 */
int register_builtin_modules() {
    // Register procengine_cpp as a built-in module
    // This makes it available without needing the .pyd/.so file
    if (PyImport_AppendInittab("procengine_cpp", PyInit_procengine_cpp) == -1) {
        std::cerr << "Error: Could not register procengine_cpp module" << std::endl;
        return -1;
    }
    return 0;
}

/**
 * Run the main Python entry point.
 */
int run_main(int argc, char* argv[], const std::string& exe_dir) {
    // Convert argv to wchar_t for Python
    std::vector<wchar_t*> wargv(argc);
    for (int i = 0; i < argc; ++i) {
        size_t len = strlen(argv[i]) + 1;
        wargv[i] = new wchar_t[len];
        mbstowcs(wargv[i], argv[i], len);
    }

    // Set program name
    Py_SetProgramName(wargv[0]);

    // Initialize Python
    Py_Initialize();
    if (!Py_IsInitialized()) {
        std::cerr << "Error: Failed to initialize Python interpreter" << std::endl;
        return -1;
    }

    // Set sys.argv
    PySys_SetArgvEx(argc, wargv.data(), 0);

    // Add exe_dir to sys.path (in case Py_SetPath didn't work fully)
    PyObject* sys_path = PySys_GetObject("path");
    if (sys_path) {
        PyObject* dir_str = PyUnicode_FromString(exe_dir.c_str());
        PyList_Insert(sys_path, 0, dir_str);
        Py_DECREF(dir_str);
    }

    // Import and run main module
    int result = 0;
    PyObject* main_module = PyImport_ImportModule("main");
    if (main_module) {
        PyObject* main_func = PyObject_GetAttrString(main_module, "main");
        if (main_func && PyCallable_Check(main_func)) {
            PyObject* ret = PyObject_CallObject(main_func, nullptr);
            if (ret) {
                if (PyLong_Check(ret)) {
                    result = static_cast<int>(PyLong_AsLong(ret));
                }
                Py_DECREF(ret);
            } else {
                PyErr_Print();
                result = -1;
            }
            Py_XDECREF(main_func);
        } else {
            std::cerr << "Error: main.main() function not found" << std::endl;
            PyErr_Print();
            result = -1;
        }
        Py_DECREF(main_module);
    } else {
        std::cerr << "Error: Could not import main module" << std::endl;
        PyErr_Print();
        result = -1;
    }

    // Clean up
    Py_Finalize();

    for (int i = 0; i < argc; ++i) {
        delete[] wargv[i];
    }

    return result;
}

int main(int argc, char* argv[]) {
    // Get executable directory
    std::string exe_dir = get_executable_dir();

    // Change to executable directory
    fs::current_path(exe_dir);

    // Register built-in modules (before Py_Initialize)
    if (register_builtin_modules() != 0) {
        return 1;
    }

    // Setup Python paths
    setup_python_paths(exe_dir);

    // Run the game
    return run_main(argc, argv, exe_dir);
}
