"""Seed registry and deterministic PRNG wrapper.

This module provides the :class:`SeedRegistry` class which manages a
single root seed and produces deterministic sub-seeds for named
subsystems.  Registries can spawn child registries for hierarchical
seeding, allowing each world chunk or subsystem to operate from its own
independent seed while remaining reproducible.  The implementation
follows the determinism rules laid out in ``AGENTS.md``:

* A single 64-bit ``root_seed`` is the source of truth.
* ``splitmix64`` is used to derive deterministic sub-seeds.
* All random number generation uses NumPy's ``PCG64`` engine.

Example
-------
>>> registry = SeedRegistry(1234)
>>> child = registry.spawn("chunk_0_0")
>>> rng = child.get_rng("terrain")
>>> rng.integers(0, 10)
7

The same call sequence will always produce the same results when using
the same ``root_seed``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict

import numpy as np


_MASK64 = 0xFFFFFFFFFFFFFFFF


def _splitmix64(x: int) -> int:
    """Generate a new 64-bit seed from ``x`` using the splitmix64 algorithm."""

    x = (x + 0x9E3779B97F4A7C15) & _MASK64
    z = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9 & _MASK64
    z = (z ^ (z >> 27)) * 0x94D049BB133111EB & _MASK64
    return z ^ (z >> 31)


@dataclass
class SeedRegistry:
    """Maintain deterministic sub-seeds derived from a root seed."""

    root_seed: int
    _counter: int = 0
    _seeds: Dict[str, int] = field(default_factory=dict)

    def get_subseed(self, name: str) -> int:
        """Return a deterministic sub-seed for ``name``.

        The same ``name`` will always map to the same sub-seed. New names
        are generated by advancing a counter through ``splitmix64``.
        """

        if name not in self._seeds:
            self._counter += 1
            seed_input = self.root_seed + self._counter
            self._seeds[name] = _splitmix64(seed_input)
        return self._seeds[name]

    def get_rng(self, name: str) -> np.random.Generator:
        """Return a ``numpy.random.Generator`` seeded for ``name``."""

        subseed = self.get_subseed(name)
        bit_gen = np.random.PCG64(subseed)
        return np.random.Generator(bit_gen)

    def spawn(self, name: str) -> "SeedRegistry":
        """Return a new :class:`SeedRegistry` derived from ``name``.

        The spawned registry uses a deterministic sub-seed and can be used
        to seed child systems such as individual world chunks without
        interfering with the parent's name space.
        """

        subseed = self.get_subseed(name)
        return SeedRegistry(subseed)


__all__ = ["SeedRegistry"]

